title: Hacking Thursday
remote_theme: chrisrhymes/bulma-clean-theme@v0.13.3
livereload: true
plugins:
  - jekyll-remote-theme
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
feed:
  path: /feed/index.xml
  categories:
    - weeklynote
    - blog
