title: Hacking Thursday
remote_theme: chrisrhymes/bulma-clean-theme@v0.13.3
livereload: true
incremental: true
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
feed:
  path: /feed/index.xml
  categories:
    - weeklynote
    - blog
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
